name             'circonus-broker'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures the Circonus broker'
long_description 'Installs/Configures the Circonus broker'
version          '0.3.0'

depends 'yum'
depends 'ntp'
