name             'circonus-broker'
maintainer       'Blake Irvin'
maintainer_email 'blake.irvin@gmail.com'
issues_url 'https://github.com/bixu/circonus-broker/issues'
source_url 'https://github.com/bixu/circonus-broker'
license          'MIT'
description      'Installs/Configures the Circonus broker'
long_description 'Installs/Configures the Circonus broker'
version          '0.3.3'

depends 'yum'
depends 'ntp'
